### ISSUE TITLE
"No Such File or Directory" when using relative folder

### ISSUE THREAD

**Issue by cetra3** [Michael-F-Bryan/include_dir#29]
Having issues with the expansion of the `include_bytes` macro in the generated assets file.  It appears to try and include files relative to the output directory, as opposed to where the build.rs file is located.

I.e, 

I have a `build/` folder which lives in the same place as `Cargo.toml` and `build.rs`.   

When I run `cargo check` or `cargo build`, it creates the `assets.rs` file in the following location:

```
target/debug/build/example-034c9cad8640c442/out/
```

Then it tries to find files there, and fails:

```
couldn't read /Users/cetra/Desktop/example/back/target/debug/build/example-034c9cad8640c442/out/build/index.html: No such file or directory (os error 2)
```

**Comment by kdar** [comment]
Experiencing the same issue. The example given by this repo doesn't work as is on Rust nightly at least.

**Comment by Michael-F-Bryan** [comment]
This should be fixed now. Previously the build script implementation would try to include directories relative to the output directory whereas now the proc macro does everything relative to `CARGO_MANIFEST_DIR`, which is much more intuitive.

**Comment by melMass** [comment]
>  which is much more intuitive.

Oh I think it should be specified somewhere as it's not working like the builtin include_str which is relative to the file:
<img width=512px src="https://user-images.githubusercontent.com/7041726/200205165-3a8ab490-5c35-412b-b460-c322f79e5aec.png"/>

**Comment by melMass** [comment]
Ok :) after posting the second screenshot I tried from my workspace root and it does work, IMHO it should behave like the builtins

Both `DATAMODEL_STR` & `MIGRATIONS_DIR` reference the same `prisma` directory in the screenshot: 

<img width=512 src="https://user-images.githubusercontent.com/7041726/200206379-3e59b249-ae73-414c-92c4-d83ed079657e.png"/>

**Comment by Michael-F-Bryan** [comment]
> Oh I think it should be specified somewhere as it's not working like the builtin include_str which is relative to the file

This is not possible because the method for accessing the file an item is from ([`Span::source_file()`](https://doc.rust-lang.org/stable/proc_macro/struct.Span.html#method.source_file)) isn't stable yet. The `include_str!()` macro doesn't have this limitation because it is built into the compiler.

[The crate docs](https://docs.rs/include_dir/latest/include_dir/#environment-variables) suggest using paths relative to the `$CARGO_MANIFEST_DIR` environment variable:

> When invoking the [include_dir!()](https://docs.rs/include_dir/latest/include_dir/macro.include_dir.html) macro you should try to avoid using relative paths because rustc makes no guarantees about the current directory when it is running a procedural macro.
> 
> Environment variable interpolation can be used to remedy this. You might want to read the [Environment Variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) section of The Cargo Book for a list of variables provided by cargo.
> 
> Most crates will want to use the $CARGO_MANIFEST_DIR or $OUT_DIR variables. For example, to include a folder relative to your crate you might use include_dir!("$CARGO_MANIFEST_DIR/assets").
