### ISSUE TITLE
`cargo build` never returns

### ISSUE THREAD

**Issue by pulse0ne** [Michael-F-Bryan/include_dir#39]
Running `cargo build` on `1.38.0-nightly` never completes. I have a really beefy machine (16-core/32-thread CPU, 64GB RAM), and I can't get a binary to build with just a 450K directory being included with `include_dir!`.  CPU is pinned at 100% on one core, but the build just hangs indefinitely (I've been waiting for 2 hours now). Memory usage doesn't look terrible or unexpected, I just don't know why `include_dir!` would cause `rustc` to not be able to complete.

**Comment by Michael-F-Bryan** [comment]
Hmm... That's really odd. Is there anything special about the directory? For example, does it have symlinks or lots of little files?

The way `include_dir!()` works is (roughly) to traverse the directory tree, emitting an `include_bytes!("path/to/file.txt")` for each item and building up a tree with a bunch of `'static` items. So maybe `rustc` is expanding the `include_bytes!()` macros into a long `&[u8]` when `include_dir!()` returns, then trying to parse the really long array literals takes forever?

**Comment by pulse0ne** [comment]
Yeah, it's super odd. It's only 3 files: an index.html file, a javascript file, and a css file. No symlinks, no unusual encoding, nothing odd about the directories or files or anything.

I actually had implemented something like this awhile back (it even had the same name: [include_dir](https://gitlab.com/tsnedigar/include_dir)), but this was before procedural macros were a thing so it was a compiler plugin (not sure if those are even a thing anymore). Mine was definitely clunkier to use than yours, so I was excited to see an implementation that used procedural macros, and I'm really hoping it's just something simple that can be worked out.

 I have noticed a disparity in the time it takes to do an `include_bytes!` during compilation between  `1.35.0-stable` and `1.38.0-nightly`. Although looking at the macro code in the compiler's baseline, it  doesn't look like anything has changed functionally. If it doesn't appear for anyone else, feel free to close this issue, but I am curious if anyone else is able to reproduce this on `1.38.0-nightly`. I will create a minimal example and test it across a couple versions of rustc and let you know what I find.

**Comment by pulse0ne** [comment]
Alright, feel free to close this. I can't get a minimal working example to reproduce this, so it must be some weird interaction among this, `rocket`, or some other dependency.

**Comment by Michael-F-Bryan** [comment]
If you can reproduce it again, try to do a build with `RUSTFLAGS="-Z time-passes"` (well I think that's the right flags for time-passes). That should print out how long each stage of compilation takes so we can figure out where the problem is.

**Comment by Ploppz** [comment]
I have the same problem in stable rust, version 1.37.0. Compilation hangs indefinitely.
The directory I'm trying to include is `spec/target/docs`, where `spec` is another crate inside the crate I'm trying to build. Obviously my `spec` crate is not built at this time so I wouldn't expect any weird interactions there, as it should just be some arbitrary folder from the perspective of `cargo build` in the root project.
The files total 1 MB, 46 files.
