### ISSUE TITLE
Resolve symlinks

### ISSUE THREAD

**Issue by jbabyhacker** [Michael-F-Bryan/include_dir#54]
I am interested in building out symlink support so that links are followed. I'm OK with doing the work, but I want make sure this functionality will be accepted. Any interest?

**Comment by Michael-F-Bryan** [comment]
Shouldn't symlinks be supported out of the box? When traversing the included directory the OS should let you read the contents of a symlinked directory, and `include_bytes!()` should read symlinked files correctly.
