### ISSUE TITLE
Changes in included files do not trigger a rebuild

### ISSUE THREAD

**Issue by tobx** [Michael-F-Bryan/include_dir#77]
When using `cargo build` a change in an included file does not trigger a rebuild.

I am currently using this build script as a workaround:

```rust
// build.rs
fn main() {
    println!("cargo:rerun-if-changed=src/include");
}
```

Someone in the beginners channel of the official Rust Discord server wrote:

> In theory a macro that includes data should cause rustc to emit metadata about which files it included which cargo would read, but I don't know if that actually works in practice, or if that crate hanldes that correctly

I thought I should mention this here.

**Comment by Michael-F-Bryan** [comment]
This is actually [already implemented](https://adventures.michaelfbryan.com/posts/bringing-include_dir-into-the-modern-era/#better-dependency-tracking), but you need to explicitly opt-in using the `nightly` feature flag because it's not available on stable yet.

**Comment by jlkiri** [comment]
Weird, I've installed nightly toolchain but there is no rebuild with `cargo +nightly build` even though I change the files.
