### ISSUE TITLE
Can't reproduce README's example (glob feature)

### ISSUE THREAD

**Issue by Poulpy** [Michael-F-Bryan/include_dir#84]
Hello !

I want to list all files under a directory, with glob. I tried reproducing the README's example, but the code doesn't seem to run inside the block (I checked with a println!()), the one with the feature glob enabled.
 
I did that : 
```rust
use include_dir::{Dir, include_dir};

static SPEC_DIR: Dir<'_> = include_dir!("resources/spec");


fn main() {
    #[cfg(feature = "glob")]
    {
        let glob = "v2.3/messages/*.xsd";
        for entry in SPEC_DIR.find(glob).unwrap() {
            println!("Found {}", entry.path().display());
        }
    }
}
```

Is there anything wrong with my code ?

Thank you !

Edit: I'm using include_dir's version 0.7.2

**Comment by Michael-F-Bryan** [comment]
The `#[cfg(feature = "glob")]` is [an attribute](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition/conditional-compilation.html) which only compiles the code within the block when the `glob` feature is enabled in your `Cargo.toml`. It's what `include_dir` uses to let people opt into the extra glob functionality.

You probably want to remove the block and attribute, and make sure your `Cargo.toml` looks something like this:

```toml
[dependencies]
include_dir = { version = "^0.7.2", features = ["glob"] }
```

**Comment by Poulpy** [comment]
Thank you it works ! That was a silly error ^^'
Thanks a lot :D !
