### ISSUE TITLE
include_dir generates function calls that need promotion, leading to issues with Rust 1.79+

### ISSUE THREAD

**Issue by RalfJung** [Michael-F-Bryan/include_dir#99]
[Apparently](https://users.rust-lang.org/t/code-compiles-in-1-78-0-but-not-in-1-79-0/113038), this crate generates code like
```rust
Some(include_dir::Dir::new(
        "",
        &[include_dir::DirEntry::File(include_dir::File::new(
            "test_file.txt",
            b"",
        ))],
    ))
```
It then relies on the part in `&[...]` to be const-promoted. However, const-promotion of arbitrary function calls is [problematic](https://github.com/rust-lang/rfcs/blob/master/text/3027-infallible-promotion.md), and in Rust 1.79 it has been limited to only occur in straight-line code, causing [compilation failures](https://users.rust-lang.org/t/code-compiles-in-1-78-0-but-not-in-1-79-0/113038) for some users of this crate.

The intended way to obtain `'static` references to things computed by `const fn` is to make this explicitly `const` -- either via `const { ... }` blocks, or (when support for older versions of Rust is required), via explicit `const` items:
```rust
Some(include_dir::Dir::new(
        "",
        {
            const ENTRIES: &'static [DirEntry<'static>] = &[include_dir::DirEntry::File(include_dir::File::new(
                "test_file.txt",
                b"",
            ))];
            ENTRIES
        },
    ))
```
Would be good to get this crate updated to avoid problems related to promotion of function calls. :)

**Comment by Michael-F-Bryan** [comment]
This was odd. I tried running the crate's tests with 1.79 and `nightly`, and it built just fine 🤔 

I've made the fix anyway. Let's see if it resolves things for other people.

**Comment by RalfJung** [comment]
Thanks for the quick fix!

> This was odd. I tried running the crate's tests with 1.79 and nightly, and it built just fine 🤔

Yeah, https://github.com/rust-lang/rust/pull/121557 is rather odd, making it tricky to write a good test. This still works fine:
```rust
pub static ASSETS_DIR: Option<include_dir::Dir<'_>> = Some(include_dir::include_dir!("$CARGO_MANIFEST_DIR/assets"));
```
but putting the `include_dir!` inside an `if` breaks it. It's kind of a hack but for backcompat reasons it's hard to do better...
